set(PIO_ENV_NAME "")
set(PIO_BOARD_DIR "")
if(CONFIG_PIO_ENV_MARAUDER_V4_OG)
  set(PIO_ENV_NAME "Marauder-v4-OG")
  set(PIO_BOARD_DIR "marauder-v4og")
endif()
if(CONFIG_PIO_ENV_MARAUDER_V61)
  set(PIO_ENV_NAME "Marauder-v61")
  set(PIO_BOARD_DIR "marauder-v4og")
endif()
if(CONFIG_PIO_ENV_AWOK_TOUCH)
  set(PIO_ENV_NAME "Awok-Touch")
  set(PIO_BOARD_DIR "marauder-v4og")
endif()
if(CONFIG_PIO_ENV_M5STACK_CORES3)
  set(PIO_ENV_NAME "m5stack-cores3")
  set(PIO_BOARD_DIR "m5stack-cores3")
endif()
if(CONFIG_PIO_ENV_LILYGO_T5_EPAPER_S3_PRO)
  set(PIO_ENV_NAME "lilygo-t5-epaper-s3-pro")
  set(PIO_BOARD_DIR "lilygo-t5-epaper-s3-pro")
endif()
if(CONFIG_PIO_ENV_LILYGO_T_DISPLAY_S3_TOUCH)
  set(PIO_ENV_NAME "lilygo-t-display-S3-touch")
  set(PIO_BOARD_DIR "lilygo-t-display-s3-touch")
endif()
if(CONFIG_PIO_ENV_LILYGO_T_DECK_PRO)
  set(PIO_ENV_NAME "lilygo-t-deck-pro")
  set(PIO_BOARD_DIR "lilygo-t-deck-pro")
endif()
if(CONFIG_PIO_ENV_CYD_2432S028)
  set(PIO_ENV_NAME "CYD-2432S028")
  set(PIO_BOARD_DIR "CYD-2432S028")
endif()
if(CONFIG_PIO_ENV_CYD_2_USB)
  set(PIO_ENV_NAME "CYD-2-USB")
  set(PIO_BOARD_DIR "CYD-2432S028")
endif()
if(CONFIG_PIO_ENV_CYD_2432W328C)
  set(PIO_ENV_NAME "CYD-2432W328C")
  set(PIO_BOARD_DIR "CYD-2432S028")
endif()
if(CONFIG_PIO_ENV_CYD_2432W328C_2)
  set(PIO_ENV_NAME "CYD-2432W328C_2")
  set(PIO_BOARD_DIR "CYD-2432S028")
endif()
if(CONFIG_PIO_ENV_CYD_2432S024R)
  set(PIO_ENV_NAME "CYD-2432S024R")
  set(PIO_BOARD_DIR "CYD-2432S028")
endif()
if(CONFIG_PIO_ENV_CYD_2432W328R)
  set(PIO_ENV_NAME "CYD-2432W328R")
  set(PIO_BOARD_DIR "CYD-2432S028")
endif()
if(CONFIG_PIO_ENV_CYD_2432S022C)
  set(PIO_ENV_NAME "CYD-2432S022C")
  set(PIO_BOARD_DIR "CYD-2432S028")
endif()
if(CONFIG_PIO_ENV_CYD_2432S032C)
  set(PIO_ENV_NAME "CYD-2432S032C")
  set(PIO_BOARD_DIR "CYD-2432S028")
endif()
if(CONFIG_PIO_ENV_CYD_2432S032R)
  set(PIO_ENV_NAME "CYD-2432S032R")
  set(PIO_BOARD_DIR "CYD-2432S028")
endif()
if(CONFIG_PIO_ENV_CYD_3248S035C)
  set(PIO_ENV_NAME "CYD-3248S035C")
  set(PIO_BOARD_DIR "CYD-2432S028")
endif()
if(CONFIG_PIO_ENV_CYD_3248S035R)
  set(PIO_ENV_NAME "CYD-3248S035R")
  set(PIO_BOARD_DIR "CYD-2432S028")
endif()
if(CONFIG_PIO_ENV_CYD_8048S043C)
  set(PIO_ENV_NAME "CYD-8048S043C")
  set(PIO_BOARD_DIR "CYD-2432S028")
endif()
if(CONFIG_PIO_ENV_CYD_8048W550C)
  set(PIO_ENV_NAME "CYD-8048W550C")
  set(PIO_BOARD_DIR "CYD-2432S028")
endif()
if(CONFIG_PIO_ENV_CYD_3248W535C)
  set(PIO_ENV_NAME "CYD-3248W535C")
  set(PIO_BOARD_DIR "CYD-2432S028")
endif()
if(CONFIG_PIO_ENV_CYD_4827S043R)
  set(PIO_ENV_NAME "CYD-4827S043R")
  set(PIO_BOARD_DIR "CYD-2432S028")
endif()
if(CONFIG_PIO_ENV_LILYGO_T_DONGLE_S3_TFT)
  set(PIO_ENV_NAME "lilygo-t-dongle-s3-tft")
  set(PIO_BOARD_DIR "lilygo-t-dongle-s3-tft")
endif()
if(CONFIG_PIO_ENV_LILYGO_T_DECK)
  set(PIO_ENV_NAME "lilygo-t-deck")
  set(PIO_BOARD_DIR "lilygo-t-deck")
endif()
if(CONFIG_PIO_ENV_HEADLESS_ESP32_4MB)
  set(PIO_ENV_NAME "headless-esp32-4mb")
  set(PIO_BOARD_DIR "ESP-General")
endif()
if(CONFIG_PIO_ENV_HEADLESS_ESP32_8MB)
  set(PIO_ENV_NAME "headless-esp32-8mb")
  set(PIO_BOARD_DIR "ESP-General")
endif()
if(CONFIG_PIO_ENV_HEADLESS_ESP32S3_4MB)
  set(PIO_ENV_NAME "headless-esp32s3-4mb")
  set(PIO_BOARD_DIR "ESP-General")
endif()
if(CONFIG_PIO_ENV_HEADLESS_ESP32S3_8MB)
  set(PIO_ENV_NAME "headless-esp32s3-8mb")
  set(PIO_BOARD_DIR "ESP-General")
endif()
if(CONFIG_PIO_ENV_HEADLESS_ESP32S3_16MB)
  set(PIO_ENV_NAME "headless-esp32s3-16mb")
  set(PIO_BOARD_DIR "ESP-General")
endif()
if(CONFIG_PIO_ENV_M5STACK_CPLUS1_1)
  set(PIO_ENV_NAME "m5stack-cplus1_1")
  set(PIO_BOARD_DIR "m5stack-cplus1_1")
endif()
if(CONFIG_PIO_ENV_M5STACK_C)
  set(PIO_ENV_NAME "m5stack-c")
  set(PIO_BOARD_DIR "m5stack-cplus1_1")
endif()
if(CONFIG_PIO_ENV_M5STACK_CARDPUTER)
  set(PIO_ENV_NAME "m5stack-cardputer")
  set(PIO_BOARD_DIR "m5stack-cardputer")
endif()
if(CONFIG_PIO_ENV_SMOOCHIEE_BOARD)
  set(PIO_ENV_NAME "smoochiee-board")
  set(PIO_BOARD_DIR "smoochiee-board")
endif()
if(CONFIG_PIO_ENV_LILYGO_T_EMBED)
  set(PIO_ENV_NAME "lilygo-t-embed")
  set(PIO_BOARD_DIR "lilygo-t-embed-cc1101")
endif()
if(CONFIG_PIO_ENV_LILYGO_T_EMBED_CC1101)
  set(PIO_ENV_NAME "lilygo-t-embed-cc1101")
  set(PIO_BOARD_DIR "lilygo-t-embed-cc1101")
endif()
if(CONFIG_PIO_ENV_LILYGO_T_DISPLAY_S3_AMOLED)
  set(PIO_ENV_NAME "lilygo-t-display-S3-amoled")
  set(PIO_BOARD_DIR "lilygo-t-display-s3-amoled")
endif()
if(CONFIG_PIO_ENV__NEW_DEVICE_MODEL)
  set(PIO_ENV_NAME "_New-Device-Model")
  set(PIO_BOARD_DIR "_New-Device-Model")
endif()
if(CONFIG_PIO_ENV_M5STACK_CORE)
  set(PIO_ENV_NAME "m5stack-core")
  set(PIO_BOARD_DIR "m5stack-core")
endif()
if(CONFIG_PIO_ENV_M5STACK_CORE_4MB)
  set(PIO_ENV_NAME "m5stack-core-4Mb")
  set(PIO_BOARD_DIR "m5stack-core")
endif()
if(CONFIG_PIO_ENV_M5STACK_CPLUS2)
  set(PIO_ENV_NAME "m5stack-cplus2")
  set(PIO_BOARD_DIR "m5stack-cplus2")
endif()
if(CONFIG_PIO_ENV_LILYGO_T_LORA_PAGER)
  set(PIO_ENV_NAME "lilygo-t-lora-pager")
  set(PIO_BOARD_DIR "lilygo-t-lora-pager")
endif()
if(CONFIG_PIO_ENV_LILYGO_T_DISPLAY_S3_PRO)
  set(PIO_ENV_NAME "lilygo-t-display-S3-pro")
  set(PIO_BOARD_DIR "lilygo-t-display-s3-pro")
endif()
if(CONFIG_PIO_ENV_ELECROW_24B)
  set(PIO_ENV_NAME "elecrow-24B")
  set(PIO_BOARD_DIR "elecrow")
endif()
if(CONFIG_PIO_ENV_ELECROW_28B)
  set(PIO_ENV_NAME "elecrow-28B")
  set(PIO_BOARD_DIR "elecrow")
endif()
if(CONFIG_PIO_ENV_ELECROW_35B)
  set(PIO_ENV_NAME "elecrow-35B")
  set(PIO_BOARD_DIR "elecrow")
endif()
if(CONFIG_PIO_ENV_ELECROW_35BV2_2)
  set(PIO_ENV_NAME "elecrow-35Bv2_2")
  set(PIO_BOARD_DIR "elecrow")
endif()
if(CONFIG_PIO_ENV_M5STACK_CORE2)
  set(PIO_ENV_NAME "m5stack-core2")
  set(PIO_BOARD_DIR "m5stack-core2")
endif()
if(CONFIG_PIO_ENV_MARAUDER_MINI)
  set(PIO_ENV_NAME "Marauder-Mini")
  set(PIO_BOARD_DIR "marauder-mini")
endif()
if(CONFIG_PIO_ENV_MARAUDER_V7)
  set(PIO_ENV_NAME "Marauder-v7")
  set(PIO_BOARD_DIR "marauder-mini")
endif()
if(CONFIG_PIO_ENV_AWOK_MINI)
  set(PIO_ENV_NAME "Awok-Mini")
  set(PIO_BOARD_DIR "marauder-mini")
endif()
if(NOT PIO_ENV_NAME)
  set(PIO_ENV_NAME "m5stack-cardputer")
  set(PIO_BOARD_DIR "m5stack-cardputer")
endif()
